version: "3"

volumes: 
  hook-data:
  
services: 
  hook:
    image: containerize/webhook
    ports: 
      - "9000:9000"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - hook-data:/var/webhook
